server:
  port: 8069    #default port where the service will be started
 
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:  
  rabbitmq:
       host : localhost
       port : 5672
       username : guest
       password : guest 
  application:
    name: user-service   #current service name to be used by the eureka server
  #cloud:
   # config:
    #   url: http:\\localhost:8888
  datasource:
    url: jdbc:h2:mem:userDB
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  h2:
    console:
       enabled: true
  jpa:
    properties:
       hibernate.generate_statistics: false
       hibernate.format_sql:  true
    hibernate.ddl-auto: none
    show-sql: true
   
management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc. 
 
logging:
  level:
    com.syscho.library.admin: DEBUG
    com.syscho.user.service.AlbumServiceClient: DEBUG
     
jwt:
  secret:
     key: "BATMAN"



feign: 
    hystrix:
        enable: true
       